on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: hylswind/reusable-workflow@main
    - run: |
        ls -alh
        echo "From reusable workflow"
        echo ${{ inputs.name }}
        echo ${{ inputs.version }}
