on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "From reusable workflow"
        echo ${{ inputs.name }}
        echo ${{ inputs.version }}
